% For now, I am considering having this program solve both 6x6 and 9x9 puzzles.
% In the future, they might be two distinct programs.
clc, clear;

% puzzle is a test matrix representing an unsolved sudoku board with zeros for
% blanks. In the future, input is likely to be parsed and then the puzzle array 
% created by this program.
puzzle = [0 0 0 2 6 0 7 0 1;...
          6 8 0 0 7 0 0 9 0;...
          1 9 0 0 0 4 5 0 0;...
          8 2 0 1 0 0 0 4 0;...
          0 0 4 6 0 2 9 0 0;...
          0 5 0 0 0 3 0 2 8;...
          0 0 9 3 0 0 0 7 4;...
          0 4 0 0 5 0 0 3 6;...
          7 0 3 0 1 8 0 0 0];
          
puzzle6 = [0 2 0 0 4 5;...
           0 0 3 2 6 0;...
           6 3 0 4 0 0;...
           2 0 4 5 3 0;...
           0 0 0 6 2 0;...
           4 6 0 0 0 3];

[m, n] = size(puzzle);

% The following statement will be useful when the puzzle is not hard-coded. I
% need to do the same sort of thing for 6x6 puzzles if I decided to keep these
% in the same program.
assert(and(m==9, n==9), 'Provided puzzle is not a 9x9 matrix.')

% I sum the columns and rows here to see if they add up to 45. Adding 1 through
% 9 together equals 45, so in the late stages these sums will be useful.
columnSums = sum(puzzle);
rowSums = sum(puzzle');

% nonetSums produces a 3x3 array of sums, the sums that one would get by adding
% the values in a 3x3 block of a normal sudoku board.
nonetSums = [sum(sum(puzzle(1:3, 1:3))) ...
             sum(sum(puzzle(4:6, 1:3))) ...
             sum(sum(puzzle(7:9, 1:3)));...
             sum(sum(puzzle(1:3, 4:6))) ...
             sum(sum(puzzle(4:6, 4:6))) ...
             sum(sum(puzzle(7:9, 4:6)));...
             sum(sum(puzzle(1:3, 7:9))) ...
             sum(sum(puzzle(4:6, 7:9))) ...
             sum(sum(puzzle(7:9, 7:9)))];

% sextetSums produces a 2x3 array of sums, the sums one would get by adding the 3x2 blocks
% in small sudoku boards
sextetSums = [sum(sum(puzzle6(1:2, 1:3))) ...
              sum(sum(puzzle6(1:2, 4:6)));...
              sum(sum(puzzle6(3:4, 1:3))) ...
              sum(sum(puzzle6(3:4, 4:6)));...
              sum(sum(puzzle6(5:6, 1:3))) ...
              sum(sum(puzzle6(5:6, 4:6)))]
